# Generated by Django 4.1.2 on 2022-10-11 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "restaurant",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.restaurant",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="restaurantadmin", name="restaurant",),
        migrations.DeleteModel(name="KitchenStaff",),
        migrations.DeleteModel(name="RestaurantAdmin",),
    ]
